name: airflow_fraud_detection

x-airflow-common:
  &airflow-common
  build:
    context: .              # chemin vers ton Dockerfile
    dockerfile: Dockerfile
  env_file:               
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
    - AIRFLOW__LOAD_EXAMPLES=False    
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./scripts:/opt/airflow/scripts  
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - postgres


services:
  postgres:
    image: postgres:13
    container_name: airflow_fraud_detection_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    container_name: airflow_fraud_detection_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Loic \
          --lastname Valentini \
          --role Admin \
          --email valentini.loic@gmail.com
    restart: "no"

  webserver:
    <<: *airflow-common
    container_name: airflow_fraud_detection_webserver
    command: webserver
    ports:
      - "8085:8080"
    restart: always

  scheduler:
    <<: *airflow-common
    container_name: airflow_fraud_detection_scheduler
    command: scheduler
    restart: always

volumes:
  postgres-db-volume:
