# Image de base Airflow officielle
FROM apache/airflow:2.8.0

# Installation des dépendances Python nécessaires pour ton projet
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
